export default {
  'eslint': 'eslint',
  'this': 'this',
  'img': 'img',
  '$index': '$index',
  'class': 'class',
  'style': 'style',
  'computed': 'computed',
  'transition': 'transition',
  'v-on': 'v-on',
  '@': '@',
  'props': 'props',
  'component': 'component',
  'template': 'template',
  'sync': 'sync',
  'slot': 'slot',
  'v-for': 'v-for',
  'fragment': 'fragment',
  'v-show': 'v-show',
  'v-if': 'v-if',
  'track-by': 'track-by',
  'filter': 'filter',
  'vuex': 'vuex',
  'vue-router': 'vue-router',
  'vue-resource': 'vue-resource',
  '组件通信': '组件通信',
  '组件实例': '组件实例',
  '热替换': '热替换',
  'hot reload': 'hot reload',
  'webpack': 'webpack',
  '箭头符号': '箭头符号',
  '字面量': '字面量',
  'v-cloak': 'v-cloak',
  'sass': 'sass'
}
